---
title: "Routt NF Assisted Migration Plan"
author: "Katie Nigro"
date: "2024-10-07"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#load libraries
library(terra)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(egg)
library(tmap)
library(sf)
library(raster)
library(grid)
library(gridExtra)
library(tidyterra)
```

```{r}
##read in species climate ranges
clim_abla <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/species_climate_niches/clim_abla.csv")
clim_piar <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/species_climate_niches/clim_piar.csv")
clim_pifl <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/species_climate_niches/clim_pifl.csv")
clim_pipo <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/species_climate_niches/clim_pipo.csv")
clim_pipu <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/species_climate_niches/clim_pipu.csv")
clim_psme <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/species_climate_niches/clim_psme.csv")
clim_pien <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/species_climate_niches/engelmann_clim.csv")
clim_pico <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/species_climate_niches/clim_pico.csv")
```

```{r}
################################## Functions ###################################
#### Function 1 
# function to load rasters for climate variables for a set time period
# "vars" is a list of climate variable names selected from the SST dataset
# "time_period" is the time period that the climate variables should be selected for
# again among the options available in the SST
load_clims_katie <- function(vars,time_period) {
  # initialize empty list
  clim_list <- list()
  # for each climate variable in the "vars" input, load the corresponding raster dataset
  # for the time period specified with "time_period", and append that raster to "clim_list"
  clim_list <- lapply(vars, function(clim) {
    rast(paste("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/",time_period,"/tifs/",clim,"_wgs84.tif",sep=""))
  })
  # return the climate rasters
  return(clim_list)
}

#### Function 2
# function to extract summary data for the climate center and transfer limit of
# a set of seed/breeding zones for use in zone-based SST runs. "breeding_zones" 
# is a set of zones in terra vector format, "time_period" is the time period you
# want to extract summary data for(typically "historic" 1961-1990 conditions), 
# and "vars" is a list of climate variable names from the SST climate data.
extract_clims_katie <- function(breeding_zones,time_period,vars) {
  # initialize empty vectors
  bz_df <- c()
  full_df <- c()
  zmax <- c()
  zmin <- c()
  zmean <- c()
  zmedian <- c()
  zcenter <- c()
  zTL <- c()
  variable <- c()
  # loop through each climate variable in "vars"
  for (var in vars) {
    # load climate data using the load_clims function
    clim <- load_clims_katie(var,time_period)
    # loop through each zone in the set of zones
    for (z in 1:nrow(breeding_zones)) {
      # extract maximum value of the variable in the zone
      zmax[z] <- as.numeric(extract(clim[[1]], breeding_zones[z], max, na.rm = TRUE)[2])
      # extract minimum value of the variable in the zone
      zmin[z] <- as.numeric(extract(clim[[1]], breeding_zones[z], min, na.rm = TRUE)[2])
      # extract mean value of the variable in the zone
      zmean[z] <- as.numeric(extract(clim[[1]], breeding_zones[z], mean, na.rm = TRUE)[2])
      # extract median value of the variable in the zone
      zmedian[z] <- as.numeric(extract(clim[[1]], breeding_zones[z], median, na.rm = TRUE)[2])
      # calculate the transfer limit as half the range of variation in the zone
      zTL[z] <- (zmax[[z]]-zmin[[z]])/2
      # calculate the center of the range
      zcenter[z] <- zmax[[z]]-zTL[[z]]
      # save the name of the climate variable
      variable[z] <- var
      # print progress
      print(paste("Extracting",var,"for zone",z,"out of",nrow(breeding_zones)))
    }
    # make a temp dataframe copying the data for each zone
    bz_df <- as.data.frame(breeding_zones)
    # append climate summary data
    bz_df$zone_max <- zmax
    bz_df$zone_min <- zmin
    bz_df$zone_mean <- zmean
    bz_df$zone_median <- zmedian
    bz_df$zone_center <- zcenter
    bz_df$zone_transfer_limit <- zTL
    bz_df$clim_var <- variable
    # add to master dataframe
    full_df <- rbind(full_df,bz_df)
  }
  return(full_df)
}


#### Function 3
## load in a list of climate rasters and a list of climate summaries for a zone
## and perform the SST using the climate center of the zone to calculate match 
## scores - this function uses the median climate value as the climate center
SST_zone_median <- function(clims,zone_clims,region) {
  y_n <- 0
  for (clim in 1:length(clims)) {
    clim_rast <- mask(crop(clims[[clim]],region),region)/10
    clim_center <- zone_clims[[clim]]$zone_median
    clim_TL <- zone_clims[[clim]]$zone_transfer_limit
    clim_y <- (abs(clim_rast-clim_center)/clim_TL)^2
    y_n <- y_n + clim_y
  }
  m <- (-1*(sqrt(y_n)-1))*100
  m[m < 0] <- 0
  set.names(m,"match score")
  return(m)
}

################################################################################

###################### Load in data for region and zones #######################
######getting R2 data in order
adminboundaries <- vect("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ArcGIS/S_USA.AdministrativeRegion/S_USA.AdministrativeRegion.shp")
region_2 <- adminboundaries %>% 
  subset(subset = adminboundaries$REGION=="02")
region_2 <- project(region_2, "+proj=longlat +ellps=WGS84 +no_defs")

region_2_4 <- adminboundaries %>% 
  subset(subset = adminboundaries$REGION %in% c("02","03","04")) %>% 
  project("+proj=longlat +ellps=WGS84 +no_defs")

region_2_grid <- rast(region_2, nrow=200, ncol=200)
region_2_rast <- rasterize(region_2, region_2_grid)

##seed zones
co_breedingzones<- vect("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/co_breedingzones.shp")

routt_10000_bz <- co_breedingzones %>% filter(SEED_COL_Z %in% c(26,29,55) & r2elev_z10==10000)

ggplot()+
  geom_spatvector(data=routt_10000_bz, aes(fill=factor(SEED_COL_Z)))

#### Input Data
# status update
print("loading in input data...")
# load in shape file for region and set projection
region_2_4
# load in shape file for breeding zones and set projection
breeding_zones <- project(routt_10000_bz,"+proj=longlat +ellps=WGS84 +no_defs")

# remove undefined breeding zones labeled "0" and "1" - this may not be an issue for your zones
# but we have some that are undefined (below and above the defined bands)
breeding_zones <- breeding_zones[breeding_zones$ZONE_NO!="0",]
breeding_zones <- breeding_zones %>% 
  mutate(breeding_z = seq(1,nrow(breeding_zones),1))

################################################################################

###################### Extract climate data from zones #########################
# time period to use as the point of reference for the SST - in this case historic conditions
# climate variables to use for the SST - in this case the defaults for the SST

filenames <- c("AHM","bFFP","CMD","DD_18","DD_0","DD5","eFFP","EMT","Eref","EXT","FFP","MAP","MAT","MCMT","MSP","MWMT","NFFD","PAS","PPT_sm","PPT_wt","RH","Tave_sm","Tave_wt","TD","SHM")

filenames_edited <- c("AHM","bFFP","CMD","DD18","DD0","DD5","eFFP","EMT","Eref","EXT","FFP","MAP","MAT","MCMT","MSP","MWMT","NFFD","PAS","PPTsm","PPTwt","RH","Tavesm","Tavewt","TD","SHM")

normtif <- rast(paste0("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/Normal_1961_1990_bioclim/Normal_1961_1990/Normal_1961_1990_bioclim/Normal_1961_1990_",filenames,".tif",sep=""))

names(normtif)<- paste(filenames_edited,"_historic_1970s", sep="")

#2000's normal
clim2000s <- rast(paste0("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/Normal_1991_2020_bioclim/Normal_1991_2020_bioclim/Normal_1991_2020_",filenames,".tif",sep=""))

names(clim2000s) <- paste(filenames_edited,"_historic_2000s", sep="") 

##2020's projections
clim2020s <- rast(paste0("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ensemble_8GCMs_ssp585_2011_2040_bioclim/ensemble_8GCMs_ssp585_2011_2040/ensemble_8GCMs_ssp585_2011_2040_bioclim/ensemble_8GCMs_ssp585_2011_2040_",filenames,".tif",sep=""))

names(clim2020s) <- paste(filenames_edited,"_ssp585_2020s", sep="")  

##2050's projections
clim2050s <- rast(paste0("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ensemble_8GCMs_ssp585_2041_2070_bioclim/ensemble_8GCMs_ssp585_2041_2070/ensemble_8GCMs_ssp585_2041_2070_bioclim/ensemble_8GCMs_ssp585_2041_2070_",filenames,".tif",sep=""))

names(clim2050s) <- paste(filenames_edited,"_ssp585_2050s", sep="") 

##2080's projections
clim2080s <- rast(paste0("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ensemble_8GCMs_ssp585_2071_2100_bioclim/ensemble_8GCMs_ssp585_2071_2100/ensemble_8GCMs_ssp585_2071_2100_bioclim/ensemble_8GCMs_ssp585_2071_2100_",filenames,".tif",sep=""))

names(clim2080s) <- paste(filenames_edited,"_ssp585_2080s", sep="")  

all_climate <- c(normtif, clim2000s, clim2020s, clim2050s, clim2080s)

 # initialize empty vectors
  bz_df <- c()
  full_df <- c()
  zmax <- c()
  zmin <- c()
  zmean <- c()
  zmedian <- c()
  zcenter <- c()
  zTL <- c()
  variable <- c()
# loop through each climate variable in "vars"
  for (i in 1:nlyr(all_climate)) {
    # loop through each zone in the set of zones
    for (z in 1:nrow(breeding_zones)) {
      # extract maximum value of the variable in the zone
      zmax[z] <- as.numeric(extract(all_climate[[i]], breeding_zones[z], max, na.rm = TRUE)[2])
      # extract minimum value of the variable in the zone
      zmin[z] <- as.numeric(extract(all_climate[[i]], breeding_zones[z], min, na.rm = TRUE)[2])
      # extract mean value of the variable in the zone
      zmean[z] <- as.numeric(extract(all_climate[[i]], breeding_zones[z], mean, na.rm = TRUE)[2])
      # extract median value of the variable in the zone
      zmedian[z] <- as.numeric(extract(all_climate[[i]], breeding_zones[z], median, na.rm = TRUE)[2])
      # calculate the transfer limit as half the range of variation in the zone
      zTL[z] <- (zmax[[z]]-zmin[[z]])/2
      # calculate the center of the range
      zcenter[z] <- zmax[[z]]-zTL[[z]]
      # save the name of the climate variable
      variable[z] <- names(all_climate[[i]])
      # print progress
      print(paste("Extracting",all_climate[[i]],"for zone",z,"out of",nrow(breeding_zones)))
    }
    # make a temp dataframe copying the data for each zone
    bz_df <- as.data.frame(breeding_zones)
    # append climate summary data
    bz_df$zone_max <- zmax
    bz_df$zone_min <- zmin
    bz_df$zone_mean <- zmean
    bz_df$zone_median <- zmedian
    bz_df$zone_center <- zcenter
    bz_df$zone_transfer_limit <- zTL
    bz_df$clim_var <- variable
    # add to master dataframe
    full_df <- rbind(full_df,bz_df)
  }

routt_climate_stats <- full_df %>% 
  separate(clim_var, into = c("climvar","carbon","period"), remove = TRUE)

ggplot(routt_climate_stats)+
  geom_point(aes(x=period, y=zone_center, shape=factor(ZONE_NO), color=period))+
  facet_wrap(~climvar, scales="free")+
  scale_color_manual(values=c("black","green","cyan3","yellow","red"))
  


clim_allspecies<- bind_rows(clim_abla %>% mutate(species="abla"),
          clim_piar %>% mutate(species="piar"),
          clim_pifl %>% mutate(species="pifl"),
          clim_pipo %>% mutate(species="pipo"),
          clim_pipu %>% mutate(species="pipu"),
          clim_psme %>% mutate(species="psme"),
          clim_pien %>% mutate(species="pien"),
          clim_pico %>% mutate(species="pico"))

all_climate_wide <- routt_climate_stats %>% 
  dplyr::select(c(ZONE_NO, period, climvar, zone_center)) %>% 
  pivot_wider(names_from = climvar, values_from = zone_center)

ggplot(clim_allspecies, aes(x=nffd, y=map))+
  geom_hex(alpha=0.7)+
  facet_wrap(~species, scales="free")+
  geom_point(data=all_climate_wide, aes(x=NFFD, y=MAP, col=period, shape=factor(ZONE_NO)))

ggplot(clim_allspecies, aes(x=mcmt/10, y=shm/10))+
  geom_hex(alpha=0.7)+
  facet_wrap(~species, scales="free")+
  geom_point(data=all_climate_wide, aes(x=MCMT, y=SHM, col=period, shape=factor(ZONE_NO)))

```

```{r}
###look for seedlots
###I need to figure which "breeding zones" we are interested - this is how the tif files are labeled. 

co_breedingzones_df <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/co_breeding_zones.csv")
co_breedingzones_df %>% 
  filter(SEED_COL_Z %in% c(26,29,55) & r2elev_z10 == "10000")

##breeding zones 430. 431, and 434 are the zones for the 10000ft band in the Routt NF area of interest

##read in nursery seed sources
bseed<- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/nursery inventories/Bessey_info/20230707_besseylots_editedlatlongs.csv")
lpseed<- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/nursery inventories/LuckyPeak_inventory_2022_editedlatlongs.csv")
cdaseed <- read.csv("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/ASCC/ASCC/nursery inventories/CdA_inventory_2023_editedlatlongs.csv")

bseed_vect <- bseed %>% 
  filter(!alt_lat=="") %>% 
  filter(!is.na(alt_lat)) %>% 
  mutate(alt_lat=as.numeric(alt_lat), alt_long=ifelse(alt_long > 0, as.numeric(alt_long)*-1, as.numeric(alt_long))) %>% 
  vect(geom=c("alt_long","alt_lat"), crs= "+proj=longlat +ellps=WGS84 +no_defs")

lpseed_vect <- lpseed %>% 
  filter(!alt_lat=="") %>% 
  filter(!is.na(alt_lat)) %>% 
  mutate(alt_lat=as.numeric(alt_lat), alt_long=ifelse(alt_long > 0, as.numeric(alt_long)*-1, as.numeric(alt_long))) %>% 
  vect(geom=c("alt_long","alt_lat"), crs= "+proj=longlat +ellps=WGS84 +no_defs")

cdaseed_vect <-cdaseed %>% 
  filter(!alt_lat=="") %>% 
  filter(!is.na(alt_lat)) %>% 
  mutate(alt_lat=as.numeric(alt_lat), alt_long=ifelse(alt_long > 0, as.numeric(alt_long)*-1, as.numeric(alt_long))) %>% 
  vect(geom=c("alt_long","alt_lat"), crs= "+proj=longlat +ellps=WGS84 +no_defs")
##########

historic430 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/430_historic.tif")
historic430_bseed_extract <- extract(historic430, bseed_vect)
historic430_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>50)
historic430_lpseed_extract <- extract(historic430, lpseed_vect)
historic430_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

present430 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/430_present.tif")
present430_bseed_extract <- extract(present430, bseed_vect)
present430_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
present430_lpseed_extract <- extract(present430, lpseed_vect)
present430_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

early430 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/430_85_early.tif")
early430_bseed_extract <- extract(early430, bseed_vect)
early430_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
early430_lpseed_extract <- extract(early430, lpseed_vect)
early430_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

mid430 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/430_85_mid.tif")
mid430_bseed_extract <- extract(mid430, bseed_vect)
mid430_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
mid430_lpseed_extract <- extract(mid430, lpseed_vect)
mid430_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

late430 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/430_85_late.tif")
late430_bseed_extract <- extract(late430, bseed_vect)
late430_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
late430_lpseed_extract <- extract(late430, lpseed_vect)
late430_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

##
historic431 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/431_historic.tif")
historic431_bseed_extract <- extract(historic431, bseed_vect)
historic431_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>50)
historic431_lpseed_extract <- extract(historic431, lpseed_vect)
historic431_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

present431 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/431_present.tif")
present431_bseed_extract <- extract(present431, bseed_vect)
present431_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
present431_lpseed_extract <- extract(present431, lpseed_vect)
present431_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

early431 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/431_85_early.tif")
early431_bseed_extract <- extract(early431, bseed_vect)
early431_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
early431_lpseed_extract <- extract(early431, lpseed_vect)
early431_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

mid431 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/431_85_mid.tif")
mid431_bseed_extract <- extract(mid431, bseed_vect)
mid431_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
mid431_lpseed_extract <- extract(mid431, lpseed_vect)
mid431_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

late431 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/431_85_late.tif")
late431_bseed_extract <- extract(late431, bseed_vect)
late431_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
late431_lpseed_extract <- extract(late431, lpseed_vect)
late431_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

##
historic434 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/434_historic.tif")
historic434_bseed_extract <- extract(historic434, bseed_vect)
historic434_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>50)
historic434_lpseed_extract <- extract(historic434, lpseed_vect)
historic434_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

present434 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/434_present.tif")
present434_bseed_extract <- extract(present434, bseed_vect)
present434_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
present434_lpseed_extract <- extract(present434, lpseed_vect)
present434_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

early434 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/434_85_early.tif")
early434_bseed_extract <- extract(early434, bseed_vect)
early434_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
early434_lpseed_extract <- extract(early434, lpseed_vect)
early434_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

mid434 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/434_85_mid.tif")
mid434_bseed_extract <- extract(mid434, bseed_vect)
mid434_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
mid434_lpseed_extract <- extract(mid434, lpseed_vect)
mid434_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

late434 <- rast("C:/Users/KatherineNigro/Box/01. katherine.nigro Workspace/R2 reforestation/R2-reforestation/SST_standalone/SST_standalone/results/test_results/434_85_late.tif")
late434_bseed_extract <- extract(late434, bseed_vect)
late434_bseed_extract %>% 
  bind_cols(as.data.frame(bseed_vect)) %>% 
  filter(`match score`>0)
late434_lpseed_extract <- extract(late434, lpseed_vect)
late434_lpseed_extract %>% 
  bind_cols(as.data.frame(lpseed_vect)) %>% 
  filter(`match score`>0)

```
